# This is a basic workflow to help you get started with Actions test

name: CD MULE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
          java-version: 1.11
    - name: Build and Test
      run: mvn -B clean deploy --file pom.xml -DskipTests=true | sudo apt-get update | npm install -g anypoint-cli-v4 
    - name: Install Anypoint 
      run: anypoint-cli-v4 plugins:install anypoint-cli-exchange-plugin | echo "repository variable :$vars.HELLO_WORLD"
    - name: Upload Asset to Exchange
      env: 
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }} 
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
          ANYPOINT_ORG_ID: ${{ secrets.ANYPOINT_ORGID }}
      run: |
        ls target/*.jar | head -1
        artifactName1=$(ls target/*.jar | head -1)
        anypoint-cli-v4 exchange:asset:upload \
        --name "hellomule4" \
        --files='{"mule-application.jar": "'"$artifactName1"'"}' \
        --type app \
        hello-mule4/1.0.0
    - name: Stamp artifact file name with commit hash
      run: |
        artifactName1=$(ls target/*.jar | head -1)
        commitHash=$(git rev-parse --short "$GITHUB_SHA")
        artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/.$commitHash.jar/g")
        mv $artifactName1 $artifactName2
    - name: Deploy to CloudHUB
      env: 
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }} 
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
          ANYPOINT_ORG_ID: ${{ secrets.ANYPOINT_ORGID }}
      run: |
        anypoint-cli-v4 runtime-mgr:application:deploy hellomule2 cloudhub-us-east-2 4.4.0 hello-mule 
    - uses: actions/upload-artifact@master
      with:
          name: artifacts
          path: target/*.jar
          retention-days: 2
